// Cross-language parity test: replays internal/wire/testdata/vectors.json
// (generated by the Go reference implementation) through the exact module
// the browser runs — web/crypto.js (vendored noble scrypt + WebCrypto).
// Run: node tests/parity.mjs   (regenerate vectors: go test ./internal/wire -run TestVectors -update)
import { readFile } from 'node:fs/promises';
import { decodeCode, derive, decrypt, parseEnvelope, b64decode, toHex } from '../web/crypto.js';

const vectors = JSON.parse(await readFile(new URL('../internal/wire/testdata/vectors.json', import.meta.url), 'utf8'));
let failures = 0;
const check = (i, name, got, want) => {
  if (got !== want) { failures++; console.error(`vector ${i}: ${name} MISMATCH\n  got  ${got}\n  want ${want}`); }
};
const b64 = (u8) => btoa(String.fromCharCode(...u8));

for (const [i, v] of vectors.entries()) {
  // Also exercise typo tolerance: lowercase, dash-less, o-for-0, l-for-1.
  const typed = v.code.toLowerCase().replaceAll('-', '').replaceAll('0', 'o').replaceAll('1', 'l');
  const { locator, key } = decodeCode(typed);
  check(i, 'locator', locator, v.locator);
  check(i, 'key', toHex(key), toHex(decodeCode(v.code).key));

  const keys = await derive(key, v.pin, locator);
  check(i, 'enc_key', toHex(keys.enc), v.enc_key_hex);
  check(i, 'auth_key', toHex(keys.auth), v.auth_key_hex);
  const verifier = new Uint8Array(await crypto.subtle.digest('SHA-256', keys.auth));
  check(i, 'verifier', toHex(verifier), v.verifier_hex);

  const plain = await decrypt(keys.enc, locator, b64decode(v.ct_b64));
  check(i, 'envelope', b64(plain), v.envelope_b64);
  const { header, payload } = parseEnvelope(plain);
  check(i, 'header', JSON.stringify(header), JSON.stringify(JSON.parse(v.header_json)));
  check(i, 'payload', b64(payload), v.payload_b64);
}

if (failures) { console.error(`FAIL: ${failures} mismatch(es)`); process.exit(1); }
console.log(`OK: ${vectors.length} vectors — Go (CLI) and JS (browser) agree byte-for-byte`);
