// Cross-language parity test: replays internal/wire/testdata/vectors.json
// (generated by the Go reference implementation) through the exact code the
// browser uses — web/scrypt.js (vendored noble scrypt) + WebCrypto AES-GCM.
// Run: node tests/parity.mjs   (regenerate vectors: go test ./internal/wire -run TestVectors -update)
import { readFile } from 'node:fs/promises';
import { scryptAsync } from '../web/scrypt.js';

const SCRYPT = { N: 2 ** 16, r: 8, p: 1, dkLen: 64 };
const B58 = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';

// Duplicated from web/app.js (kept tiny and spec-frozen; drift is caught here
// because these must match the Go outputs byte-for-byte).
function b58decode(s) {
  let zeros = 0;
  while (zeros < s.length && s[zeros] === '1') zeros++;
  let n = 0n;
  for (const ch of s) {
    const v = B58.indexOf(ch);
    if (v < 0) throw new Error('invalid base58');
    n = n * 58n + BigInt(v);
  }
  const out = [];
  while (n > 0n) { out.unshift(Number(n & 0xffn)); n >>= 8n; }
  return new Uint8Array([...new Array(zeros).fill(0), ...out]);
}
const toHex = (u8) => [...u8].map((b) => b.toString(16).padStart(2, '0')).join('');
const normalizePin = (pin) => pin.toUpperCase().replace(/[ -]/g, '')
  .replaceAll('O', '0').replaceAll('I', '1').replaceAll('L', '1');

const vectors = JSON.parse(await readFile(new URL('../internal/wire/testdata/vectors.json', import.meta.url), 'utf8'));
let failures = 0;
const check = (i, name, got, want) => {
  if (got !== want) { failures++; console.error(`vector ${i}: ${name} MISMATCH\n  got  ${got}\n  want ${want}`); }
};

for (const [i, v] of vectors.entries()) {
  const key = b58decode(v.k_b58);
  const salt = b58decode(v.salt_b58);
  const pinBytes = new TextEncoder().encode(normalizePin(v.pin));
  const password = new Uint8Array([...key, ...pinBytes]);
  const root = await scryptAsync(password, salt, SCRYPT);
  check(i, 'enc_key', toHex(root.slice(0, 32)), v.enc_key_hex);
  check(i, 'auth_key', toHex(root.slice(32, 64)), v.auth_key_hex);
  const verifier = new Uint8Array(await crypto.subtle.digest('SHA-256', root.slice(32, 64)));
  check(i, 'verifier', toHex(verifier), v.verifier_hex);

  const blob = Uint8Array.from(atob(v.ct_b64), (c) => c.charCodeAt(0));
  const aesKey = await crypto.subtle.importKey('raw', root.slice(0, 32), 'AES-GCM', false, ['decrypt']);
  const plain = new Uint8Array(await crypto.subtle.decrypt(
    { name: 'AES-GCM', iv: blob.slice(0, 12), additionalData: new TextEncoder().encode('sharebuff/v2.' + v.id_b58) },
    aesKey,
    blob.slice(12),
  ));
  check(i, 'envelope', btoa(String.fromCharCode(...plain)), v.envelope_b64);

  // Parse the envelope exactly the way web/app.js does.
  const hlen = new DataView(plain.buffer, plain.byteOffset).getUint32(0);
  if (hlen > 4096 || 4 + hlen > plain.length) { failures++; console.error(`vector ${i}: envelope header out of bounds`); continue; }
  const header = JSON.parse(new TextDecoder().decode(plain.slice(4, 4 + hlen)));
  const wantHeader = JSON.parse(v.header_json);
  check(i, 'header', JSON.stringify(header), JSON.stringify(wantHeader));
  const payload = plain.slice(4 + hlen);
  check(i, 'payload', btoa(String.fromCharCode(...payload)), v.payload_b64);
}

if (failures) { console.error(`FAIL: ${failures} mismatch(es)`); process.exit(1); }
console.log(`OK: ${vectors.length} vectors — Go (CLI) and JS (browser) agree byte-for-byte`);
